###
# @name createAsset
POST http://localhost:3000/assets
Content-Type: application/json

{
  "name": "NVidia",
  "symbol": "NVDA",
  "price": 13000,
  "image": "NVDA.png"
}

###

# @assetId = {{ createAsset.response.body._id }}
@assetId = 3491734c-4aa4-4bdf-9f56-be6417ba70fd

###
GET http://localhost:3000/assets

###
GET http://localhost:3000/assets/A1

###
# @name createWallet
POST http://localhost:3000/wallets

###

# @walletId = {{ createWallet.response.body._id }}
@walletId = d3c6c8b4-727b-446c-a282-ea807c1d745d

###
GET http://localhost:3000/wallets

###
GET http://localhost:3000/wallets/{{ walletId }}

###
POST http://localhost:3000/wallets/{{ walletId }}/assets
Content-Type: application/json

{
  "assetId": "{{ assetId }}",
  "shares": 145
}

###
POST http://localhost:3000/orders
Content-Type: application/json

{
  "walletId": "{{ walletId }}",
  "assetId": "{{ assetId }}",
  "shares": 15,
  "price": 50,
  "type": "BUY"
}

###
GET http://localhost:3000/orders?walletId={{ walletId }}